"use client";

import { motion } from "framer-motion";
import Link from "next/link";
import { useAuth } from "@/components/providers/AuthProvider";

const features = [
  {
    icon: (
      <svg className="w-7 h-7" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" aria-hidden="true">
        <path strokeLinecap="round" strokeLinejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 0 1 2.25-2.25h13.5A2.25 2.25 0 0 1 21 7.5v11.25m-18 0A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75m-18 0v-7.5A2.25 2.25 0 0 1 5.25 9h13.5A2.25 2.25 0 0 1 21 11.25v7.5" />
      </svg>
    ),
    title: "Calendar Intelligence",
    desc: "Syncs your Google Calendar to detect events and curate gear for ski trips, weddings, and more.",
  },
  {
    icon: (
      <svg className="w-7 h-7" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" aria-hidden="true">
        <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904 9 18.75l-.813-2.846a4.5 4.5 0 0 0-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 0 0 3.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 0 0 3.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 0 0-3.09 3.09ZM18.259 8.715 18 9.75l-.259-1.035a3.375 3.375 0 0 0-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 0 0 2.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 0 0 2.455 2.456L21.75 6l-1.036.259a3.375 3.375 0 0 0-2.455-2.456ZM16.894 20.567 16.5 21.75l-.394-1.183a2.25 2.25 0 0 0-1.423-1.423L13.5 18.75l1.183-.394a2.25 2.25 0 0 0 1.423-1.423l.394-1.183.394 1.183a2.25 2.25 0 0 0 1.423 1.423l1.183.394-1.183.394a2.25 2.25 0 0 0-1.423 1.423Z" />
      </svg>
    ),
    title: "Gemini AI Engine",
    desc: "Hyper-personalized recommendations and WCAG-compliant alt-text generated by Google Gemini.",
  },
  {
    icon: (
      <svg className="w-7 h-7" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" aria-hidden="true">
        <path strokeLinecap="round" strokeLinejoin="round" d="M15 10.5a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
        <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 10.5c0 7.142-7.5 11.25-7.5 11.25S4.5 17.642 4.5 10.5a7.5 7.5 0 1 1 15 0Z" />
      </svg>
    ),
    title: "Local First Sourcing",
    desc: "Items within 5 miles are prioritized for in-store pickup, cutting last-mile carbon emissions.",
  },
  {
    icon: (
      <svg className="w-7 h-7" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" aria-hidden="true">
        <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75 11.25 15 15 9.75m-3-7.036A11.959 11.959 0 0 1 3.598 6 11.99 11.99 0 0 0 3 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285Z" />
      </svg>
    ),
    title: "Zero Trust Security",
    desc: "RBAC with Firebase, Zod validation, CSP headers, rate limiting, and PCI-compliant Stripe checkout.",
  },
];

const stagger = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: { staggerChildren: 0.12 },
  },
};

const fadeUp = {
  hidden: { opacity: 0, y: 24 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5, ease: "easeOut" } },
};

export default function LandingPage() {
  const { user } = useAuth();

  return (
    <div className="min-h-screen bg-[var(--background)] text-[var(--foreground)] overflow-hidden">
      {/* Liquid Ambient Background */}
      <div className="pointer-events-none fixed inset-0 z-0">
        <motion.div 
          animate={{
            x: [0, 40, -40, 0],
            y: [0, -40, 40, 0],
          }}
          transition={{ duration: 20, repeat: Infinity, ease: "linear" }}
          className="absolute top-[-20%] left-[30%] w-[600px] h-[600px] rounded-full bg-blue-600/10 blur-[120px]" 
        />
        <motion.div 
          animate={{
            x: [0, -30, 30, 0],
            y: [0, 30, -30, 0],
          }}
          transition={{ duration: 25, repeat: Infinity, ease: "linear" }}
          className="absolute bottom-[-10%] right-[20%] w-[500px] h-[500px] rounded-full bg-emerald-500/8 blur-[100px]" 
        />
        <div className="absolute top-[40%] left-[10%] w-[300px] h-[300px] rounded-full bg-[var(--cta)]/5 blur-[80px]" />
      </div>

      {/* Hero */}
      <motion.section
        initial="hidden"
        animate="visible"
        variants={stagger}
        className="relative z-10 max-w-6xl mx-auto px-6 pt-32 pb-24 md:pt-48 md:pb-36"
      >
        <motion.p variants={fadeUp} className="text-xs font-black tracking-[0.2em] uppercase text-[var(--cta)] mb-6">
          Intelligence-Driven Retail
        </motion.p>
        <motion.h1 variants={fadeUp} className="text-6xl md:text-8xl font-black tracking-tight leading-[0.95] max-w-4xl mb-8">
          Personalized.
          <br />
          <span className="bg-gradient-to-r from-blue-500 via-emerald-400 to-[var(--cta)] bg-clip-text text-transparent">
            Sustainable.
          </span>
        </motion.h1>
        <motion.p variants={fadeUp} className="text-lg md:text-2xl text-[var(--secondary)] max-w-2xl leading-relaxed mb-12">
          The first context-aware shopping assistant that synchronizes your life with 
          local inventory to reduce waste and eliminate your last-mile footprint.
        </motion.p>
        <motion.div variants={fadeUp} className="flex flex-wrap gap-6">
          <Link
            href={user ? "/shop/discover" : "/login"}
            className="btn-cta text-lg flex items-center gap-3 group"
          >
            {user ? "Open Requisition Hub" : "Initialize Secured Session"}
            <svg className="w-5 h-5 group-hover:translate-x-1 transition-transform" fill="none" viewBox="0 0 24 24" strokeWidth={2.5} stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5 21 12m0 0-7.5 7.5M21 12H3" />
            </svg>
          </Link>
          <a
            href="#features"
            className="px-8 py-4 rounded-2xl font-bold border border-[var(--border)] hover:bg-[var(--border)] transition-colors flex items-center text-sm"
          >
            Explore Capabilities
          </a>
        </motion.div>
      </motion.section>

      {/* Features */}
      <motion.section
        id="features"
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, margin: "-100px" }}
        variants={stagger}
        className="relative z-10 max-w-6xl mx-auto px-6 pb-20"
      >
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {features.map((f) => (
            <motion.article
              key={f.title}
              variants={fadeUp}
              className="group p-8 rounded-3xl glass hover:bg-[var(--border)] transition-all cursor-default"
            >
              <div className="w-14 h-14 flex items-center justify-center rounded-2xl bg-[var(--border)] text-[var(--cta)] mb-6 group-hover:scale-110 transition-transform">
                {f.icon}
              </div>
              <h3 className="text-xl font-black mb-3">{f.title}</h3>
              <p className="text-sm text-[var(--muted)] leading-relaxed">{f.desc}</p>
            </motion.article>
          ))}
        </div>
      </motion.section>

      {/* Hardware Showroom */}
      <motion.section
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true }}
        variants={stagger}
        className="relative z-10 max-w-7xl mx-auto px-6 pb-40"
      >
        <motion.div variants={fadeUp} className="text-center mb-16">
          <h2 className="text-4xl font-black tracking-tight mb-4">The Nexus Showroom.</h2>
          <p className="text-[var(--secondary)] font-medium">Precision gear calibrated for your specific environment.</p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {[
            { img: "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80", tag: "Mountain", title: "Alpha SV Shell" },
            { img: "https://images.unsplash.com/photo-1528150177508-7cc0c36cda5c?auto=format&fit=crop&w=800&q=80", tag: "Beach", title: "Flow Longboard" },
            { img: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=800&q=80", tag: "Urban", title: "Commuter Blazer" }
          ].map((item, i) => (
            <motion.div
              key={i}
              variants={fadeUp}
              className="group relative h-[450px] rounded-[3rem] overflow-hidden glass border-2 border-[var(--border)]"
            >
              <img src={item.img} className="absolute inset-0 w-full h-full object-cover group-hover:scale-110 transition-transform duration-700" alt={item.title} />
              <div className="absolute inset-0 bg-gradient-to-t from-[var(--background)] via-transparent to-transparent opacity-60" />
              <div className="absolute bottom-10 left-10">
                <p className="text-[8px] font-black uppercase tracking-[0.3em] text-[var(--cta)] mb-2">{item.tag}</p>
                <h3 className="text-2xl font-black">{item.title}</h3>
              </div>
            </motion.div>
          ))}
        </div>
      </motion.section>

      {/* Footer */}
      <footer className="relative z-10 border-t border-[var(--border)] py-12">
        <div className="max-w-6xl mx-auto px-6 flex flex-col md:flex-row items-center justify-between gap-8">
          <div className="flex flex-col items-center md:items-start gap-2">
            <span className="text-lg font-black tracking-tighter">NexusRetail<span className="text-[var(--cta)]">.</span></span>
            <p className="text-[10px] uppercase font-bold tracking-widest text-[var(--muted)]">SECURED BY ZERO TRUST PROTOCOL</p>
          </div>
          <div className="flex gap-8 text-xs font-bold text-[var(--muted)]">
            <span>&copy; {new Date().getFullYear()} NEXUS CORP</span>
            <span>WCAG 2.1 AA COMPLIANT</span>
            <span>NEXTJS 16 STACK</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
